#!/bin/sh -e

# Slightly modified version of
# https://http://sam.aiki.info/b/git-gc-all-ferocious (see
# https://stackoverflow.com/a/14728706)

#ROOT_DIRECTORY=`git rev-parse --show-toplevel`
#git remote rm origin || true
#git tag | xargs git tag -d
#git branch -D in || true
#rm -rf "$ROOT_DIRECTORY/.git/refs/remotes/" \
#    "$ROOT_DIRECTORY/.git/refs/original/" "$ROOT_DIRECTORY/.git/*_HEAD" \
#    "$ROOT_DIRECTORY/.git/logs/"
#git for-each-ref --format="%(refname)" refs/original/ | xargs -n1 \
#    --no-run-if-empty git update-ref -d
git -c gc.reflogExpire=0 -c gc.reflogExpireUnreachable=0 -c \
    gc.rerereresolved=0 -c gc.rerereunresolved=0 -c gc.pruneExpire=now gc "$@"
